### ISSUE TITLE
Is the app compatible with "My schedule" feature from the Hoverboard

### ISSUE THREAD

**Issue by zasadnyy** [RigaDevDay/rdd-android#39]
As an attendee, I'd like to have "my schedule" synchronized between app and web.

Hoverboard have this feature, does the mobile app have it? Is it compatible with Hoverboard one?

**Comment by AlexeyBuzdin** [comment]
It should by spec, and I think it does. Asked @siga111 and @dmi3j

**Comment by luhmirin-s** [comment]
I have no idea about which "Hoverboard" are you talking about. :) Android app in current state does not sync with website. Whole concept of "My schedule" is slightly different there and it does not make sense to sync them. It most likely will be aligned (and syncing) in next iteration of this app, no promises, tho.
