### ISSUE TITLE
Sample Data for Firebase

### ISSUE THREAD

**Issue by riggaroo** [RigaDevDay/rdd-android#41]
Hi there,
First of all, thanks for making this open source! 👍  Really appreciated. 

I'm trying to get this sample up and running, would you be able to include a JSON file that is a sample of the data structure required for Firebase?

**Comment by AlexeyBuzdin** [comment]
Hi Rebecca, thank you for your kind words :)
We started the initiative to roll out the project to gdg-x, but DevFest Baltics came in our way. :) We will continue with that after new year, I guess.

Regarding jsonfile, I've created this repo https://github.com/AlexeyBuzdin/open-schedule this should be the specification of JSON we use. It's an extension of Hoverboard JSON.

Hope that helps!

**Comment by riggaroo** [comment]
Thanks @AlexeyBuzdin 👍

**Comment by AlexeyBuzdin** [comment]
@riggaroo were you able to set it up? :)

**Comment by riggaroo** [comment]
Yes thanks for your help we got it working 👍 😄
